services:
  api1:
    image: ghcr.io/vcalazans/rinha-api:latest
    container_name: rinha-api-1
    security_opt:
      - seccomp=unconfined
    environment:
      - MODE=api_uring
      - PORT=8080
      - INDEX_PATH=/data/index.bin
      - WORKERS=1
    ports:
      - "9999:9999"
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/ready"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    networks:
      - rinha

  api2:
    image: ghcr.io/vcalazans/rinha-api:latest
    container_name: rinha-api-2
    network_mode: "service:api1"
    security_opt:
      - seccomp=unconfined
    environment:
      - MODE=api_uring
      - PORT=8081
      - INDEX_PATH=/data/index.bin
      - WORKERS=1
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8081/ready"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

  lb:
    image: haproxy:alpine
    container_name: rinha-lb
    network_mode: "service:api1"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30MB"

networks:
  rinha:
    driver: bridge
