services:
  api1:
    image: ghcr.io/vcalazans/rinha-api:latest
    container_name: rinha-api-1
    user: root
    ipc: shareable
    shm_size: 8mb
    environment:
      - MODE=api_shm
      - PORT=8080
      - INDEX_PATH=/data/index.bin
      - SHM_PATH=/rinha_ring
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/ready"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "160MB"
    networks:
      - rinha

  api2:
    image: ghcr.io/vcalazans/rinha-api:latest
    container_name: rinha-api-2
    user: root
    ipc: "service:api1"
    shm_size: 8mb
    environment:
      - MODE=api_shm
      - PORT=8080
      - INDEX_PATH=/data/index.bin
      - SHM_PATH=/rinha_ring
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/ready"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "160MB"
    networks:
      - rinha

  lb:
    image: ghcr.io/vcalazans/rinha-api:latest
    container_name: rinha-lb
    user: root
    ipc: "service:api1"
    shm_size: 8mb
    environment:
      - MODE=lb
      - PORT=9999
      - SHM_PATH=/rinha_ring
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:9999/ready"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "30MB"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge
