services:
  api1:
    image: ghcr.io/vcalazans/rinha-api:uds16
    container_name: rinha-api-1
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile: 65535
    environment:
      - MODE=api_uds
      - PORT=8080
      - INDEX_PATH=/data/index.bin
      - WORKERS=1
      - UDS_LISTEN=/sockets/api1.sock
    expose:
      - "8080"
    volumes:
      - sockets:/sockets
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/ready"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "165MB"
    networks:
      - rinha

  api2:
    image: ghcr.io/vcalazans/rinha-api:uds16
    container_name: rinha-api-2
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile: 65535
    environment:
      - MODE=api_uds
      - PORT=8081
      - INDEX_PATH=/data/index.bin
      - WORKERS=1
      - UDS_LISTEN=/sockets/api2.sock
    expose:
      - "8081"
    volumes:
      - sockets:/sockets
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8081/ready"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "165MB"
    networks:
      - rinha

  lb:
    image: haproxy:2.9-alpine
    container_name: rinha-lb
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile: 65535
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "20MB"
    networks:
      - rinha

volumes:
  sockets:

networks:
  rinha:
    driver: bridge
